"""Configuration settings for AI-SwAutoMorph"""
import os

# Database configuration
DB_PATH = 'softfluid/db/ai_swautomorph.db'

# Name of print logs output file
OUTPUT_PRINT_LOGS_FILENAME = 'print_output_swautomorph.log'

# Flask configuration
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-change-in-production')
FLASK_ENV = os.environ.get('FLASK_ENV', 'development')

# CORS configuration
CORS_ORIGINS = [
    'https://wwww.swautomorph.com', 
    'https://ai-haccp.swautomorph.com'
]

# Timeouts
TIMEOUT_GITEA_HTTP_POST=30
TIMEOUT_SUBPROCESS_RUN=600
TIMEOUT_QCHAT_DEVELOPER_RUN=1800
TIMEOUT_CLEAN_SHUTDOWN=60
TIMEOUT_QCHAT_OPERATOR_RUN=1800

# Path configuration functions
def get_logs_dir():
    """Get logs directory path"""
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_dir, 'logs')

def get_qchat_paths():
    """Get qchat command paths to search"""
    home_dir = os.path.expanduser('~')
    return [
        os.path.join(home_dir, '.local', 'bin', 'qchat'),
        '/usr/local/bin/qchat',
        '/usr/bin/qchat',
        'qchat'
    ]

# Language translations
TRANSLATIONS = {
    'en': {
        'login': 'Login',
        'register': 'Register',
        'username': 'Username',
        'email': 'Email',
        'password': 'Password',
        'first_name': 'First Name',
        'last_name': 'Last Name',
        'dashboard': 'Dashboard',
        'logout': 'Logout',
        'welcome': 'Welcome',
        'available_applications': 'Available Applications',
        'add_new_application': 'Add New Application',
        'application_name': 'Application Name',
        'url': 'URL',
        'description': 'Description',
        'add_application': 'Add Application',
        'no_apps': 'No applications available yet.',
        'already_account': 'Already have an account?',
        'no_account': "Don't have an account?",
        'login_here': 'Login here',
        'register_here': 'Register here',
        'open_application': 'Open Application',
        'no_description': 'No description available',
        'app_is_running': 'App. is running',
        'app_is_not_running': 'App. is not running',
        'first_clone': 'Clone to be done',
        'clone': 'Clone',
        'reclone': 'Clone again',
        'not_cloned': 'Not Cloned',
        'start': 'Start',
        'stop': 'Stop',
        'restart': 'Restart',
        'status': 'Status',
        'logs': 'Logs',
        'start_app': 'Start Application',
        'stop_app': 'Stop Application',
        'deployment_logs': 'Deployment Logs',
        'clear_logs': 'Clear Logs',
        'hide': 'Hide',
        'select_application': 'Select Application',
        'qchat_title': 'Q Chat - GenAI Assistant to modify the code of the selected Application',
        'auto_approve': 'Auto-approve updates/writes',
        'send': 'Send',
        'qchat_placeholder': 'Type your message to Q Chat...',
        'cancel': 'Cancel',
        'edit': 'Edit',
        'delete': 'Delete',
        'users': 'Users',
        'applications': 'Applications',
        'qchat_ready': 'Your virtual developer assistant is waiting for you! Ask it for a modification to the selected software, for example: add the ability to clock in multiple times per day in the ai-haccp software.',
        'platform_subtitle': 'The Future of Software Development is Here',
        'mission_statement': 'Welcome to the next evolution of GenAI impact. After replacing IT developers, <strong>agentic AI will now replace entire IT companies</strong> that develop software.',
        'target_title': 'Built for Forward-Thinking Businesses',
        'restaurants_title': 'Restaurants & Hospitality',
        'restaurants_desc': 'Manage your digital ecosystem with AI-powered virtual developers',
        'small_business_title': 'Small Businesses',
        'small_business_desc': 'Get enterprise-level software development without the enterprise costs',
        'entrepreneurs_title': 'Entrepreneurs',
        'entrepreneurs_desc': 'Transform ideas into running applications through natural language',
        'features_title': 'What You Get',
        'virtual_devs_title': 'Virtual AI Developers',
        'virtual_devs_desc': 'Chat with AI agents to modify, deploy, and manage your applications',
        'realtime_updates_title': 'Real-time Code Updates',
        'realtime_updates_desc': 'Request changes in plain English, watch them happen instantly',
        'auto_deploy_title': 'Automated Deployment',
        'auto_deploy_desc': 'From code to production in minutes, not months',
        'multi_app_title': 'Multi-App Management',
        'multi_app_desc': 'Control multiple applications from one collaborative dashboard',
        'revolution_message': 'The software development industry as we know it is about to change forever. Get ready to get wet - the wave of agentic AI is here.',
        'all_rights_reserved': 'All rights reserved.',
        'developed_by': 'Developed by',
        'with_help_of': 'tested by',
        'and': 'and',
        'virtual_advisor_toggle': 'My Virtual Operations Team : ask them to START / STOP / PS / RESTART / LOGS',
        'virtual_developer_toggle': 'My Virtual Developer: ask him to modify the application',
        'platform_subtitle': 'Centralized Application Deployment & Management Platform',
        'mission_statement': 'Enable GenAI agents to autonomously deploy, manage, and access web applications without human intervention.',
        'built_for_title': 'Built For',
        'genai_agents': 'GenAI Agents',
        'genai_agents_desc': 'Autonomous application deployment and management',
        'developers': 'Developers',
        'developers_desc': 'Streamlined deployment with virtual AI assistants',
        'operations_teams': 'Operations Teams',
        'operations_teams_desc': 'Multi-server deployment with automated lifecycle management',
        'key_features': 'Key Features',
        'virtual_agents': 'My Virtual IT Team Agents',
        'virtual_agents_desc': 'AI Developer & Operations assistants for code and deployment',
        'app_lifecycle': 'Application Lifecycle',
        'app_lifecycle_desc': 'CLONE, START, STOP, RESTART, PS, LOGS management',
        'sso_auth': 'SSO Authentication',
        'sso_auth_desc': 'Token-based authentication with Gitea integration',
        'multi_server': 'Multi-Server Support',
        'multi_server_desc': 'Capacity-based server allocation and management',
        'billing_tracking': 'Billing & Cost Tracking',
        'billing_tracking_desc': 'Usage monitoring with automated cost calculation',
        'security': 'Security',
        'security_desc': 'ModSecurity WAF protection with OWASP CRS rules',
        'multiple_interfaces': 'Multiple Interfaces',
        'multiple_interfaces_desc': 'Web Dashboard, CLI, REST API, MCP Protocol',
        'revolution_message': 'Autonomous application deployment for the AI-driven future',
        'multi_server_short': 'Multi-Server',
        'sso_short': 'SSO',
        'virtual_agents_short': 'Virtual Agents',
        'billing_short': 'Billing',
        'waf_protected': 'WAF Protected',
        'servers': 'Servers',
        'billing': 'Billing',
        'database': 'Database',
        'deployment_logs': 'Deployment Logs',
        'app_identity': 'APPLICATION IDENTITY',
        'github_repo_url': 'Github Official Readonly Repository URL',
        'edit_application': 'Edit Application',
        'update_application': 'Update Application',
        'application_details': 'Application Details',
        'close': 'Close',
        'billing_management': 'Billing Management',
        'period': 'Period',
        'today': 'Today',
        'this_week': 'This Week',
        'this_month': 'This Month',
        'manage_costs': 'Manage Costs',
        'application_costs': 'Application Costs',
        'usage_summary': 'Usage Summary',
        'activity_log': 'Activity Log',
        'loading': 'Loading...',
        'add_user': 'Add User',
        'add_new_user': 'Add New User',
        'create_user': 'Create User',
        'edit_user': 'Edit User',
        'update_user': 'Update User',
        'manage_applications_for': 'Manage Applications for',
        'available_applications': 'Available Applications',
        'assigned_applications': 'Assigned Applications',
        'server_management': 'Server Management',
        'add_server': 'Add Server',
        'loading_servers': 'Loading servers...',
        'add_new_server': 'Add New Server',
        'server_ip': 'Server IP',
        'server_name': 'Server Name',
        'max_users': 'Max Users',
        'max_applications': 'Max Applications',
        'server_type': 'Server Type',
        'create_server': 'Create Server',
        'edit_server': 'Edit Server',
        'update_server': 'Update Server',
        'database_management': 'Database Management',
        'select_table': 'Select Table',
        'select_table_option': '-- Select Table --',
        'auth_tokens': 'Auth Tokens',
        'user_applications_ports': 'User Applications',
        'deployments': 'Deployments',
        'application_costs': 'Application Costs',
        'billing_activities': 'Billing Activities',
        'users_logs': 'Users Logs',
        'refresh': 'Refresh',
        'add_record': 'Add Record',
        'select_table_view_data': 'Select a table to view data',
        'add_new_record': 'Add New Record',
        'save': 'Save',
        'edit_record': 'Edit Record',
        'update': 'Update',
        'ready_deployment_commands': 'Ready for deployment commands...',
        'developer': 'Developer',
        'operations': 'Operations',
        'virtual_developer': 'Virtual Developer',
        'select_application': 'Select Application',
        'select_application_option': '-- Select Application --',
        'describe_changes_placeholder': 'Describe what changes you want the AI to make to the code...',
        'auto_approve': 'Auto Approve',
        'virtual_operations': 'Virtual Operator',
        'ask_question_placeholder': 'Ask your question or describe what you need...',
        'deployment_status': 'Deployment Status',
        'automorph_session': 'Automorph Session',
        'instructions_ai_agent': 'Instructions for AI Agent',
        'describe_changes_ai_placeholder': 'Describe what changes you want the AI to make to the code...',
        'interactive_session': 'Interactive Session',
        'step_by_step_interaction': 'Check this for step-by-step interaction with the AI agent',
        'start_automorph': 'Start Automorph',
        'replace_it_team': 'Replace Your IT Team with AI Agents',
        'stop_waiting_message': 'Stop waiting for developers and IT support. Our AI agents handle everything - from coding new features to deploying and managing your applications. No more tickets, no more delays, no more expensive IT contracts.',
        'what_ai_agents_do': 'What AI Agents Do For You',
        'ai_developer_desc': 'Modifies your app code instantly based on your requests in plain English',
        'ai_operations_desc': 'Deploys, starts, stops, and monitors your applications 24/7',
        'instant_results': 'Instant Results',
        'instant_results_desc': 'Changes happen in minutes, not weeks or months',
        'why_choose_ai': 'Why Choose AI Over Human IT',
        'cost_savings': 'Cost Savings',
        'cost_savings_desc': 'No salaries, no benefits, no training costs',
        'availability_247': '24/7 Availability',
        'availability_247_desc': 'AI agents never sleep, take breaks, or go on vacation',
        'instant_response': 'Instant Response',
        'instant_response_desc': 'No waiting in ticket queues or scheduling meetings',
        'perfect_execution': 'Perfect Execution',
        'perfect_execution_desc': 'No human errors, consistent quality every time',
        'unlimited_scalability': 'Unlimited Scalability',
        'unlimited_scalability_desc': 'Handle multiple projects simultaneously',
        'always_learning': 'Always Learning',
        'always_learning_desc': 'AI agents improve with every interaction',
        'disruption_warning': 'The IT industry is being disrupted RIGHT NOW. Companies using AI agents are moving 10x faster than those still relying on human IT teams. Don\'t get left behind.',
        'configuration': 'Configuration',
        'user_management': 'User Management',
        'server_management': 'Server Management',
        'database_management': 'Database Management',
        'virtual_agents_ready': 'Virtual Agents ready. Select an application and action to get started.',
        'modify_code_option': '👨‍💻 MODIFY the App. (IT Dev)',
        'start_app_option': '▶️ START the App. (IT Ops)',
        'stop_app_option': '⏹️ STOP the App. (IT Ops)',
        'display_logs_option': '📋 DISPLAY logs of the App. (IT Ops)',
        'display_ps_option': '🔍 VERIFY status of the App. (IT Ops)',
        'account_activation_message_title': '⚠️ Account Activation Required',
        'account_activation_message_body': 'Your account will not be activated by default. It will be activated by AUTOMORPH since the usage generates costs.',
        'dev_modify_code_request1': 'I need a developer specialist to modify the code of the application',
        'dev_modify_code_request2': 'Please, hereafter is the specification of the request :',
        'ops_exec_request1': 'I need an operations specialist to execute the',
        'ops_exec_request2': 'action on the application',
        'select_app_tooltip': 'Select an application on which you want to ask the virtual IT specialists to perform an action'
    },
    'fr': {
        'login': 'Connexion',
        'register': 'Inscription',
        'username': "Nom utilisateur",
        'email': 'Email',
        'password': 'Mot de passe',
        'first_name': 'Prénom',
        'last_name': 'Nom',
        'dashboard': 'Tableau de bord',
        'logout': 'Déconnexion',
        'welcome': 'Bienvenue',
        'available_applications': 'Applications disponibles',
        'add_new_application': 'Ajouter une nouvelle application',
        'application_name': "Nom de l'application",
        'url': 'URL',
        'description': 'Description',
        'add_application': 'Ajouter une application',
        'no_apps': 'Aucune application disponible pour le moment.',
        'already_account': 'Vous avez déjà un compte ?',
        'no_account': "Vous n'avez pas de compte ?",
        'login_here': 'Connectez-vous ici',
        'register_here': 'Inscrivez-vous ici',
        'open_application': "Application accessible",
        'no_description': 'Aucune description disponible',
        'app_is_not_running': 'Application arrêtée',
        'app_is_running': 'Application démarrée',
        'first_clone': 'A Cloner pour la première fois',
        'clone': 'A Cloner',
        'reclone': 're-Cloner',
        'not_cloned': 'Non encore cloné',
        'start': 'Démarrer',
        'stop': 'Arrêter',
        'restart': 'Redémarrer',
        'status': 'Statut',
        'logs': 'Journaux',
        'start_app': 'Application a démarrer',
        'stop_app': 'Application a arrêter',
        'deployment_logs': 'Journaux de déploiement',
        'clear_logs': 'Effacer les journaux',
        'hide': 'Masquer',
        'select_application': 'Sélectionner une application',
        'qchat_title': 'Q Chat - Assistant GenAI pour modifier le code du logiciel sélectionnée',
        'auto_approve': 'Approuver automatiquement les mises à jour/écritures',
        'send': 'Envoyer',
        'qchat_placeholder': 'Tapez votre message à Q Chat...',
        'cancel': 'Annuler',
        'edit': 'Modifier',
        'delete': 'Supprimer',
        'users': 'Utilisateurs',
        'applications': 'Applications',
        'qchat_ready': 'Votre assistant développeur virtuel vous attend ! Demandez-lui une modification pour le logiciel sélectionné, par exemple : ajoute la possibilité de pointer plusieurs fois par jour dans le logiciel ai-haccp.',
        'platform_subtitle': 'L\'Avenir du Développement Logiciel est Arrivé',
        'mission_statement': 'Bienvenue dans la prochaine évolution de l\'impact de l\'IA générative. Après avoir remplacé les développeurs IT, <strong>l\'IA agentique va maintenant remplacer des entreprises IT entières</strong> qui développent des logiciels.',
        'target_title': 'Conçu pour les Entreprises Visionnaires',
        'restaurants_title': 'Restaurants et Hôtellerie',
        'restaurants_desc': 'Gérez votre écosystème numérique avec des développeurs virtuels alimentés par l\'IA',
        'small_business_title': 'Petites Entreprises',
        'small_business_desc': 'Obtenez un développement logiciel de niveau entreprise sans les coûts d\'entreprise',
        'entrepreneurs_title': 'Entrepreneurs',
        'entrepreneurs_desc': 'Transformez vos idées en applications fonctionnelles grâce au langage naturel',
        'features_title': 'Ce que Vous Obtenez',
        'virtual_devs_title': 'Développeurs IA Virtuels',
        'virtual_devs_desc': 'Discutez avec des agents IA pour modifier, déployer et gérer vos applications',
        'realtime_updates_title': 'Mises à Jour de Code en Temps Réel',
        'realtime_updates_desc': 'Demandez des modifications en français simple, regardez-les se réaliser instantanément',
        'auto_deploy_title': 'Déploiement Automatisé',
        'auto_deploy_desc': 'Du code à la production en minutes, pas en mois',
        'multi_app_title': 'Gestion Multi-Applications',
        'multi_app_desc': 'Contrôlez plusieurs applications depuis un tableau de bord collaboratif',
        'revolution_message': 'Une industrie du développement logiciel telle que nous la connaissons va changer à jamais. Préparez-vous à être mouillés - la vague de l\'IA agentique est là.',
        'all_rights_reserved': 'Tous droits réservés.',
        'developed_by': 'Développé par',
        'with_help_of': 'testé par',
        'and': 'et',
        'virtual_advisor_toggle': 'La Team Ingénieurs Opérations virtuels : demandez-leur de START / STOP / PS / RESTART / LOGS',
        'virtual_developer_toggle': 'La Team Développeurs virtuels : demandez-leur de modifier le logiciel',
        'platform_subtitle': 'Plateforme Centralisée de Déploiement et Gestion du logiciel',
        'mission_statement': 'Permettre aux agents GenAI de déployer, gérer et accéder aux applications web de manière autonome sans intervention humaine.',
        'built_for_title': 'Conçu Pour',
        'genai_agents': 'Agents GenAI',
        'genai_agents_desc': 'Déploiement et gestion autonome du logiciel',
        'developers': 'Développeurs',
        'developers_desc': 'Déploiement simplifié avec assistants IA virtuels',
        'operations_teams': 'Équipes Opérations',
        'operations_teams_desc': 'Déploiement multi-serveurs avec gestion automatisée du cycle de vie',
        'key_features': 'Fonctionnalités Clés',
        'virtual_agents': 'Mes Informaticiens Virtuels',
        'virtual_agents_desc': 'Assistants IA Développeur et Opérations pour le code et le déploiement',
        'app_lifecycle': 'Cycle de Vie des Applications',
        'app_lifecycle_desc': 'Gestion CLONE, START, STOP, RESTART, PS, LOGS',
        'sso_auth': 'Authentification SSO',
        'sso_auth_desc': 'Authentification basée sur des tokens avec intégration Gitea',
        'multi_server': 'Support Multi-Serveurs',
        'multi_server_desc': 'Allocation et gestion de serveurs basée sur la capacité',
        'billing_tracking': 'Suivi de Facturation et Coûts',
        'billing_tracking_desc': 'Surveillance du usage avec calcul automatisé des coûts',
        'security': 'Sécurité',
        'security_desc': 'Protection ModSecurity WAF avec règles OWASP CRS',
        'multiple_interfaces': 'Interfaces Multiples',
        'multiple_interfaces_desc': 'Tableau de Bord Web, CLI, API REST, Protocole MCP',
        'revolution_message': 'Déploiement autonome du logiciel pour un avenir piloté par IA',
        'multi_server_short': 'Multi-Serveurs',
        'sso_short': 'SSO',
        'virtual_agents_short': 'Mes Informaticiens Virtuels',
        'billing_short': 'Facturation',
        'waf_protected': 'Protégé WAF',
        'servers': 'Serveurs',
        'billing': 'Facturation',
        'database': 'Base de Données',
        'deployment_logs': 'Journaux de Déploiement',
        'app_identity': 'IDENTITÉ APPLICATION',
        'github_repo_url': 'URL du Dépôt GitHub Officiel en Lecture Seule',
        'edit_application': 'Modifier le logiciel',
        'update_application': 'Mettre à Jour le logiciel',
        'application_details': 'Détails du logiciel',
        'close': 'Fermer',
        'billing_management': 'Gestion de la Facturation',
        'period': 'Période',
        'today': "Aujourd'hui",
        'this_week': 'Cette Semaine',
        'this_month': 'Ce Mois',
        'manage_costs': 'Gérer les Coûts',
        'application_costs': 'Coûts des Applications',
        'usage_summary': 'Résumé du Usage',
        'activity_log': 'Journal des Activités',
        'loading': 'Chargement...',
        'add_user': 'Ajouter Utilisateur',
        'add_new_user': 'Ajouter Nouvel Utilisateur',
        'create_user': 'Créer Utilisateur',
        'edit_user': 'Modifier Utilisateur',
        'update_user': 'Mettre à Jour Utilisateur',
        'manage_applications_for': 'Gérer les Applications pour',
        'available_applications': 'Applications Disponibles',
        'assigned_applications': 'Applications Assignées',
        'server_management': 'Gestion des Serveurs',
        'add_server': 'Ajouter Serveur',
        'loading_servers': 'Chargement des serveurs...',
        'add_new_server': 'Ajouter Nouveau Serveur',
        'server_ip': 'IP du Serveur',
        'server_name': 'Nom du Serveur',
        'max_users': 'Utilisateurs Max',
        'max_applications': 'Applications Max',
        'server_type': 'Type de Serveur',
        'create_server': 'Créer Serveur',
        'edit_server': 'Modifier Serveur',
        'update_server': 'Mettre à Jour Serveur',
        'database_management': 'Gestion de la Base de Données',
        'select_table': 'Sélectionner Table',
        'select_table_option': '-- Sélectionner Table --',
        'auth_tokens': 'Tokens pour Authentification',
        'user_applications_ports': 'Applications Utilisateur',
        'deployments': 'Déploiements',
        'application_costs': 'Coûts des Applications',
        'billing_activities': 'Activités de Facturation',
        'users_logs': 'Journaux Utilisateurs',
        'refresh': 'Actualiser',
        'add_record': 'Ajouter Enregistrement',
        'select_table_view_data': 'Sélectionner une table pour voir les données',
        'add_new_record': 'Ajouter Nouvel Enregistrement',
        'save': 'Sauvegarder',
        'edit_record': 'Modifier Enregistrement',
        'update': 'Mettre à Jour',
        'ready_deployment_commands': 'Prêt pour les commandes de déploiement...',
        'developer': 'Développeur',
        'operations': 'Opérations',
        'virtual_developer': 'Développeur Virtuel',
        'select_application': 'Sélectionner Application',
        'select_application_option': '-- Sélectionner Application --',
        'describe_changes_placeholder': 'Décrivez les modifications que vous voulez que les IA apporte au code...',
        'auto_approve': 'Approbation Automatique',
        'virtual_operations': 'Opérateur Virtuel',
        'ask_question_placeholder': 'Posez votre question ou décrivez ce dont vous avez besoin...',
        'deployment_status': 'Statut de Déploiement',
        'automorph_session': 'Session Automorph',
        'instructions_ai_agent': 'Instructions pour votre Agent IA',
        'describe_changes_ai_placeholder': 'Décrivez les modifications que vous voulez que les IA apporte au code...',
        'interactive_session': 'Session Interactive',
        'step_by_step_interaction': 'Cochez ceci pour une interaction étape par étape avec votre agent IA',
        'start_automorph': 'Démarrer Automorph',
        'replace_it_team': 'Remplacez Votre Équipe IT par des Agents IA',
        'stop_waiting_message': 'Arrêtez d\'attendre les développeurs et le support IT. Nos agents IA gèrent tout - du codage de nouvelles fonctionnalités au déploiement et à la gestion de vos applications. Fini les tickets, les retards et les contrats IT coûteux.',
        'what_ai_agents_do': 'Ce que les Agents IA Font Pour Vous',
        'ai_developer_desc': 'Modifie le code de votre application instantanément selon vos demandes en français simple',
        'ai_operations_desc': 'Déploie, démarre, arrête et surveille vos applications 24h/24 et 7j/7',
        'instant_results': 'Résultats Instantanés',
        'instant_results_desc': 'Les changements se font en minutes, pas en semaines ou mois',
        'why_choose_ai': 'Pourquoi Choisir une IA Plutôt que les IT Humaines',
        'cost_savings': 'Économies de Coûts',
        'cost_savings_desc': 'Pas de salaires, ni avantages sociaux ou de coûts de formation',
        'availability_247': 'Disponibilité 24h/24 7j/7',
        'availability_247_desc': 'Les agents IA ne dorment jamais, ne prennent pas de pauses ou de vacances',
        'instant_response': 'Réponse Instantanée',
        'instant_response_desc': 'Aucune attente dans les files de tickets ou de planification de réunions',
        'perfect_execution': 'Exécution Parfaite',
        'perfect_execution_desc': 'Aucunes erreurs humaines, qualité constante à chaque fois',
        'unlimited_scalability': 'Évolutivité Illimitée',
        'unlimited_scalability_desc': 'Gérer plusieurs projets simultanément',
        'always_learning': 'Apprentissage Continu',
        'always_learning_desc': 'Les agents IA en auto amélioration à chaque interaction',
        'disruption_warning': 'Une industrie IT est en cours de disruption MAINTENANT. Les entreprises utilisant des agents IA avancent 10 fois plus vite que celles qui dépendent encore d\'équipes IT humaines. Ne vous laissez pas distancer.',
        'configuration': 'Configuration',
        'user_management': 'Gestion des Utilisateurs',
        'server_management': 'Gestion des Serveurs',
        'database_management': 'Gestion de la Base de Données',
        'virtual_agents_ready': 'Agents Virtuels prêts. Sélectionnez une application et une action pour commencer.',
        'modify_code_option': "👨‍💻 MODIFIER l’application (Dév)",
        'start_app_option': "▶️ DÉMARRER l’application. (Ops)",
        'stop_app_option': "⏹️ ARRÊTER l’application. (Ops)",
        'display_logs_option': "📋 AFFICHER les logs de l’appli. (Ops)",
        'display_ps_option': "🔍 VERIFIER l’état de l’appli. (Ops)",
        'account_activation_message_title': '⚠️ Activation du compte nécessaire',
        'account_activation_message_body': 'Votre compte ne sera pas activé par défaut. Il sera activé par AUTOMORPH, puisque son utilisation génère des coûts.',
        'dev_modify_code_request1': 'J’ai besoin d’un spécialiste développeur pour modifier le code de l’application',
        'dev_modify_code_request2': 'Veuillez trouver ci-dessous la spécification de la demande :',
        'ops_exec_request1': 'J’ai besoin d’un spécialiste des opérations pour exécuter',
        'ops_exec_request2': 'l’action sur l’application',
        'select_app_tooltip': 'Selectionnez une application sur laquelle vous voulez demander aux informaticiens virtuels d’effectuer une action'
    }
}