"""Configuration settings for AI-SwAutoMorph"""
import os

# Database configuration
DB_PATH = 'db/ai_swautomorph.db'

# Flask configuration
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-change-in-production')
FLASK_ENV = os.environ.get('FLASK_ENV', 'development')

# CORS configuration
CORS_ORIGINS = [
    'https://ai-haccp.swautomorph.com:8102', 
    'https://ai-haccp.swautomorph.com'
]

# Language translations
TRANSLATIONS = {
    'en': {
        'login': 'Login',
        'register': 'Register',
        'username': 'Username',
        'email': 'Email',
        'password': 'Password',
        'first_name': 'First Name',
        'last_name': 'Last Name',
        'dashboard': 'Dashboard',
        'logout': 'Logout',
        'welcome': 'Welcome',
        'available_applications': 'Available Applications',
        'add_new_application': 'Add New Application',
        'application_name': 'Application Name',
        'url': 'URL',
        'description': 'Description',
        'add_application': 'Add Application',
        'no_apps': 'No applications available yet.',
        'already_account': 'Already have an account?',
        'no_account': "Don't have an account?",
        'login_here': 'Login here',
        'register_here': 'Register here',
        'open_application': 'Open Application',
        'no_description': 'No description available',
        'clone': 'Clone',
        'start': 'Start',
        'stop': 'Stop',
        'restart': 'Restart',
        'status': 'Status',
        'logs': 'Logs',
        'deployment_logs': 'Deployment Logs',
        'clear_logs': 'Clear Logs',
        'hide': 'Hide',
        'select_application': 'Select Application',
        'qchat_title': 'Q Chat - GenAI Assistant to modify the code of the selected Application',
        'auto_approve': 'Auto-approve updates/writes',
        'send': 'Send',
        'qchat_placeholder': 'Type your message to Q Chat...',
        'cancel': 'Cancel',
        'edit': 'Edit',
        'delete': 'Delete',
        'users': 'Users',
        'applications': 'Applications',
        'qchat_ready': 'Your virtual developer assistant is waiting for you! Ask it for a modification to the selected software, for example: add the ability to clock in multiple times per day in the ai-haccp software.',
        'platform_subtitle': 'The Future of Software Development is Here',
        'mission_statement': 'Welcome to the next evolution of GenAI impact. After replacing IT developers, <strong>agentic AI will now replace entire IT companies</strong> that develop software.',
        'target_title': 'Built for Forward-Thinking Businesses',
        'restaurants_title': 'Restaurants & Hospitality',
        'restaurants_desc': 'Manage your digital ecosystem with AI-powered virtual developers',
        'small_business_title': 'Small Businesses',
        'small_business_desc': 'Get enterprise-level software development without the enterprise costs',
        'entrepreneurs_title': 'Entrepreneurs',
        'entrepreneurs_desc': 'Transform ideas into running applications through natural language',
        'features_title': 'What You Get',
        'virtual_devs_title': 'Virtual AI Developers',
        'virtual_devs_desc': 'Chat with AI agents to modify, deploy, and manage your applications',
        'realtime_updates_title': 'Real-time Code Updates',
        'realtime_updates_desc': 'Request changes in plain English, watch them happen instantly',
        'auto_deploy_title': 'Automated Deployment',
        'auto_deploy_desc': 'From code to production in minutes, not months',
        'multi_app_title': 'Multi-App Management',
        'multi_app_desc': 'Control multiple applications from one collaborative dashboard',
        'revolution_message': 'The software development industry as we know it is about to change forever. Get ready to get wet - the wave of agentic AI is here.',
        'all_rights_reserved': 'All rights reserved.',
        'developed_by': 'Developed by',
        'with_help_of': 'with the help of',
        'and': 'and'
    },
    'fr': {
        'login': 'Connexion',
        'register': 'Inscription',
        'username': "Nom d'utilisateur",
        'email': 'Email',
        'password': 'Mot de passe',
        'first_name': 'Prénom',
        'last_name': 'Nom',
        'dashboard': 'Tableau de bord',
        'logout': 'Déconnexion',
        'welcome': 'Bienvenue',
        'available_applications': 'Applications disponibles',
        'add_new_application': 'Ajouter une nouvelle application',
        'application_name': "Nom de l'application",
        'url': 'URL',
        'description': 'Description',
        'add_application': 'Ajouter une application',
        'no_apps': 'Aucune application disponible pour le moment.',
        'already_account': 'Vous avez déjà un compte ?',
        'no_account': "Vous n'avez pas de compte ?",
        'login_here': 'Connectez-vous ici',
        'register_here': 'Inscrivez-vous ici',
        'open_application': "Ouvrir l'application",
        'no_description': 'Aucune description disponible',
        'clone': 'Cloner',
        'start': 'Démarrer',
        'stop': 'Arrêter',
        'restart': 'Redémarrer',
        'status': 'Statut',
        'logs': 'Journaux',
        'deployment_logs': 'Journaux de déploiement',
        'clear_logs': 'Effacer les journaux',
        'hide': 'Masquer',
        'select_application': 'Sélectionner une application',
        'qchat_title': 'Q Chat - Assistant GenAI pour modifier le code de l\'application sélectionnée',
        'auto_approve': 'Approuver automatiquement les mises à jour/écritures',
        'send': 'Envoyer',
        'qchat_placeholder': 'Tapez votre message à Q Chat...',
        'cancel': 'Annuler',
        'edit': 'Modifier',
        'delete': 'Supprimer',
        'users': 'Utilisateurs',
        'applications': 'Applications',
        'qchat_ready': 'Votre assistant développeur virtuel vous attend ! Demandez-lui une modification pour le logiciel sélectionné, par exemple : ajoute la possibilité de pointer plusieurs fois par jour dans le logiciel ai-haccp.',
        'platform_subtitle': 'L\'Avenir du Développement Logiciel est Arrivé',
        'mission_statement': 'Bienvenue dans la prochaine évolution de l\'impact de l\'IA générative. Après avoir remplacé les développeurs IT, <strong>l\'IA agentique va maintenant remplacer des entreprises IT entières</strong> qui développent des logiciels.',
        'target_title': 'Conçu pour les Entreprises Visionnaires',
        'restaurants_title': 'Restaurants et Hôtellerie',
        'restaurants_desc': 'Gérez votre écosystème numérique avec des développeurs virtuels alimentés par l\'IA',
        'small_business_title': 'Petites Entreprises',
        'small_business_desc': 'Obtenez un développement logiciel de niveau entreprise sans les coûts d\'entreprise',
        'entrepreneurs_title': 'Entrepreneurs',
        'entrepreneurs_desc': 'Transformez vos idées en applications fonctionnelles grâce au langage naturel',
        'features_title': 'Ce que Vous Obtenez',
        'virtual_devs_title': 'Développeurs IA Virtuels',
        'virtual_devs_desc': 'Discutez avec des agents IA pour modifier, déployer et gérer vos applications',
        'realtime_updates_title': 'Mises à Jour de Code en Temps Réel',
        'realtime_updates_desc': 'Demandez des modifications en français simple, regardez-les se réaliser instantanément',
        'auto_deploy_title': 'Déploiement Automatisé',
        'auto_deploy_desc': 'Du code à la production en minutes, pas en mois',
        'multi_app_title': 'Gestion Multi-Applications',
        'multi_app_desc': 'Contrôlez plusieurs applications depuis un tableau de bord collaboratif',
        'revolution_message': 'L\'industrie du développement logiciel telle que nous la connaissons va changer à jamais. Préparez-vous à être mouillés - la vague de l\'IA agentique est là.',
        'all_rights_reserved': 'Tous droits réservés.',
        'developed_by': 'Développé par',
        'with_help_of': 'avec l\'aide de',
        'and': 'et'
    }
}